steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/robotic-tide-284315/sample-app:v5', '.']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'k8s/*', 'gs://spinnaker_manifests_bucket']
images: ['gcr.io/robotic-tide-284315/sample-app:v5']


